<?php
// à vérifier ...
$classes = array (
  'dao\\dao' => 'D:\\wamp64\\www\\GestionDePresencec./dao\\Dao.php',
  'dao\\mypdo' => 'D:\\wamp64\\www\\GestionDePresencec./dao\\MyPdo.php',
  'phpmailer\\phpmailer' => 'D:\\wamp64\\www\\GestionDePresencec./phpmailer\\PhpMailer.php',
  'phpmailer\\phpmailerexception' => 'D:\\wamp64\\www\\GestionDePresencec./phpmailer\\PhpMailerException.php',
  'phpmailer\\pop' => 'D:\\wamp64\\www\\GestionDePresencec./phpmailer\\Pop3.php',
  'phpmailer\\smtp' => 'D:\\wamp64\\www\\GestionDePresencec./phpmailer\\Smtp.php',
  'entities\\address' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\Address.php',
  'entities\\course' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\Course.php',
  'entities\\document' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\Document.php',
  'entities\\hydrate' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\Hydrate.php',
  'entities\\lesson' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\Lesson.php',
  'entities\\school' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\School.php',
  'entities\\student' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\Student.php',
  'entities\\student_course' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\Student_Course.php',
  'entities\\student_lesson' => 'D:\\wamp64\\www\\GestionDePresencec./entities\\Student_Lesson.php',
  'entitiesdao\\addressdao' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesDao\\AddressDao.php',
  'entitiesdao\\coursedao' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesDao\\CourseDao.php',
  'entitiesdao\\documentdao' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesDao\\DocumentDao.php',
  'entitiesdao\\lessondao' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesDao\\LessonDao.php',
  'entitiesdao\\schooldao' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesDao\\SchoolDao.php',
  'entitiesdao\\studentdao' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesDao\\StudentDao.php',
  'entitiestools\\arraycollection' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesTools\\ArrayCollection.php',
  'entitiestools\\conversion' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesTools\\Conversion.php',
  'entitiestools\\iarraycollection' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesTools\\IArrayCollection.php',
  'entitiestools\\logger' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesTools\\Logger.php',
  'entitiestools\\parameters' => 'D:\\wamp64\\www\\GestionDePresencec./entitiesTools\\Parameters.php',
); ?>